DnDWorld.PL.WEB/Controllers/CampaignController.cs
using DnDWorld.BLL.Repositories;
using DnDWorld.BLL.Utility;
using DnDWorld.BSL.Authorization;
using DnDWorld.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DnDWorld.PL.WEB.Controllers
{
    public class CampaignController : Controller
    {
        CampaignRepo cr = new CampaignRepo();
        [UserAuth]
        public ActionResult Create()
        {
            return View();
        }

        [UserAuth, HttpPost]
        public ActionResult Create(string universeID, string planetID, string txtCampaignName, bool chkIsPublic = false)
        {
            int uniID = universeID.ToInt();
            int plaID = planetID.ToInt();


            User current = Session["user"] as User;

            Campaign newCampaign = new Campaign()
            {
                CreateDate = DateTime.Now,
                Fullname = txtCampaignName.ClearText(),
                IsOpen = false,
                IsDeleted = false,
                UpdateDate = DateTime.Now,
                UniverseID = uniID,
                PlanetID = plaID,
                OwnerID = current.UserID
            };

            bool sonuc = cr.InsertCampaign(newCampaign, out string islemSonucu);
            if (sonuc)
            {
                return RedirectToAction("ViewProfile", "Profile");
            }
            else
            {
                ViewBag.AlertMessage = islemSonucu;
                ViewBag.AlertClass = "alert alert-danger";
                return View();
            }
        }

    }
}

DnDWorld.PL.WEB/Controllers/PlanetController.cs
using DnDWorld.BLL.CustomExceptions;
using DnDWorld.BLL.Repositories;
using DnDWorld.BLL.Utility;
using DnDWorld.BSL.Authorization;
using DnDWorld.DAL;
using System.Collections.Generic;
using System.Web.Mvc;

namespace DnDWorld.PL.WEB.Controllers
{
    public class PlanetController : Controller
    {
        PlanetRepo planetRepo = new PlanetRepo();
        UniverseRepo universeRepo = new UniverseRepo();

        [UserAuth]
        public ActionResult Create() => View(universeRepo.GetUniverses((Session["user"] as User).UserID));


        [UserAuth, HttpPost]
        public ActionResult Create(string txtPlanetName, string universeID, bool chkIsPublic = false)
        {
            int uniID = universeID.ToInt();
            if (planetRepo.DoesPlanetExists(uniID, txtPlanetName))
            {
                ViewBag.AlertMessage = "Bu isim zaten kullanımda";
                ViewBag.AlertClass = "alert alert-danger";
                return View(universeRepo.GetUniverses((Session["user"] as User).UserID));
            }
            else
            {
                Planet newPlanet = new Planet()
                {
                    Fullname = txtPlanetName,
                    IsPublic = chkIsPublic,
                    OwnerID = (Session["user"] as User).UserID,
                    UniverseID = uniID

                };
                bool sonuc = planetRepo.InsertPlanet(newPlanet, out string islemSonucu);
                if (sonuc)
                {
                    return RedirectToAction("ViewProfile", "Profile", new { plaState = "suc" });
                }
                else
                {
                    ViewBag.AlertMessage = islemSonucu;
                    ViewBag.AlertClass = "alert alert-danger";
                    return View(universeRepo.GetUniverses((Session["user"] as User).UserID));
                }
            }
        }

        public ActionResult ViewPlanet(string id = "0")
        {
            int planetID = id.ToInt();
            if (planetID > 0 && planetRepo.DoesPlanetExists(planetID))
            {
                Planet planet = planetRepo.GetPlanet(planetID);
                return View(planet);
            }
            else throw new PageNotFoundException();
        }

        [UserAuth]
        public JsonResult GetPlanets(string universeID)
        {
            User currentUser = Session["user"] as User;
            List<Planet> planets = planetRepo.GetPlanets(currentUser.UserID, universeID.ToInt(), PermissionTypes.Extend);
            List<Planet> planetDTO = new List<Planet>();
            if (planets != null)
            {
                foreach (Planet planet in planets)
                {
                    planetDTO.Add(new Planet()
                    {
                        Fullname = planet.Fullname,
                        IsPublic = planet.IsPublic,
                        OwnerID = planet.OwnerID,
                        PlanetID = planet.PlanetID,
                        UniverseID = planet.UniverseID
                    });
                }
            }
            return Json(planetDTO, JsonRequestBehavior.AllowGet);
        }

    }
}

DnDWorld.PL.WEB/Controllers/SignController.cs
using DnDWorld.BLL.Repositories;
using DnDWorld.BLL.Utility;
using DnDWorld.BSL.Authorization;
using DnDWorld.DAL;
using System;
using System.Web.Mvc;
using System.Linq;

namespace DnDWorld.PL.WEB.Controllers
{
    public class SignController : Controller
    {
        UserRepo userRepo = new UserRepo();

        [NonUserAuth]
        public ActionResult SignUp() => View();
        [NonUserAuth]
        public ActionResult SignIn() => View();

        [HttpPost]
        public ActionResult SignUp(User newUser)
        {
            string islemSonucu;
            bool sonuc = userRepo.InsertUser(newUser, out islemSonucu);
            if (sonuc)
            {
                return RedirectToAction("SignIn", new { regState = "suc" });
            }
            else
            {
                ViewBag.RegState = islemSonucu;
                ViewBag.AlertState = "alert alert-danger";
                return View();
            }
        }

        [HttpPost]
        public ActionResult SignIn(string txtEmail, string txtPassword)
        {
            try
            {
                Session["user"] = userRepo.GetUser(txtEmail, txtPassword);
                if (Session["user"] != null)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.LoginState = "Giriş başarısız oldu. Kullanıcı adı veya şifre yanlış.";
                    ViewBag.AlertState = "alert alert-danger";
                    return View();
                }
            }
            catch (Exception ex)
            {
                int eventLogID = LogTypes.Error.ToInt();
                EventLog loginError = new EventLog()
                {
                    LogTypeID = eventLogID,
                    LogMessage = ex.Message,
                    CreateDate = DateTime.Now,
                    MachineName = Server.MachineName,
                    Detail = ex.InnerException + " - " + ex.StackTrace  
                };
                throw;
            }
        }
        public ActionResult SignOut()
        {
            Session["user"] = null;
            return RedirectToAction("Index", "Home");
        }
    }
}

DnDWorld.PL.WEB/Controllers/UniverseController.cs
using DnDWorld.BLL.CustomExceptions;
using DnDWorld.BLL.Repositories;
using DnDWorld.BSL.Authorization;
using DnDWorld.DAL;
using DnDWorld.BLL.Utility;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Collections.Generic;

namespace DnDWorld.PL.WEB.Controllers
{
    public class UniverseController : Controller
    {
        UniverseRepo universeRepo = new UniverseRepo();

        [UserAuth]
        public ActionResult Create() => View(universeRepo.GetUniverses((Session["user"] as User).UserID));

        [UserAuth, HttpPost]
        public ActionResult Create(string txtUniverseName, bool chkIsPublic = false)
        {
            if (universeRepo.DoesUniverseExists(txtUniverseName))
            {
                ViewBag.AlertMessage = "Bu isim zaten kullanımda";
                ViewBag.AlertClass = "alert alert-danger";
                return View(universeRepo.GetUniverses((Session["user"] as User).UserID));
            }
            else
            {
                Universe newUniverse = new Universe()
                {
                    Fullname = txtUniverseName,
                    IsPublic = chkIsPublic,
                    OwnerID = (Session["user"] as User).UserID
                };
                bool sonuc = universeRepo.InsertUniverse(newUniverse, out string islemSonucu);
                if (sonuc)
                {
                    return RedirectToAction("ViewProfile", "Profile", new { uniState = "suc" });
                }
                else
                {
                    ViewBag.AlertMessage = islemSonucu;
                    ViewBag.AlertClass = "alert alert-danger";
                    return View(universeRepo.GetUniverses((Session["user"] as User).UserID));
                }
            }
        }

        [UserAuth, HttpPost]
        public int CreateWithApi(string txtUniverseName)
        {
            if (universeRepo.DoesUniverseExists(txtUniverseName))
            {
                ViewBag.AlertMessage = "Bu isim zaten kullanımda";
                ViewBag.AlertClass = "alert alert-danger";
                return 0;
            }
            else
            {
                Universe newUniverse = new Universe()
                {
                    Fullname = txtUniverseName,
                    IsPublic = false,
                    OwnerID = (Session["user"] as User).UserID
                };

                bool sonuc = universeRepo.InsertUniverse(newUniverse, out string islemSonucu);
                return newUniverse.UniverseID;
            }
        }

        public ActionResult ViewUniverse(string id = "0")
        {
            int universeID = id.ToInt();
            if (universeID > 0 && universeRepo.DoesUniverseExists(universeID))
            {
                //Bu evren mevcut
                Universe universe = universeRepo.GetUniverse(universeID);
                return View(universe);
            }
            else throw new PageNotFoundException();
        }

        [UserAuth]
        public JsonResult GetExtendableUniverses()
        {
            User user = Session["user"] as User;
            List<Universe> universes = universeRepo.GetUniverses(user.UserID, PermissionTypes.Extend);
            List<Universe> universesDTO = new List<Universe>();
            foreach (Universe universe in universes)
            {
                universesDTO.Add(new Universe()
                {
                    Fullname = universe.Fullname,
                    IsPublic = universe.IsPublic,
                    OwnerID = universe.OwnerID,
                    UniverseID = universe.UniverseID
                });
            }
            return Json(universesDTO, JsonRequestBehavior.AllowGet);
        }
    }
}

DnDWorld.PL.WEB/Views/Shared/_Layout.cshtml
@{
    User currentUser = null;
    if (Session["user"] != null)
    {
        currentUser = Session["user"] as User;
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/css/animate.css">
    <link rel="stylesheet" href="~/Content/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Content/css/all.css">
    <link rel="stylesheet" href="~/Content/css/flaticon.css">
    <link rel="stylesheet" href="~/Content/css/themify-icons.css">
    <link rel="stylesheet" href="~/Content/css/magnific-popup.css">
    <link rel="stylesheet" href="~/Content/css/slick.css">
    <link rel="stylesheet" href="~/Content/css/style.css">
    @*<link rel="stylesheet" href="~/Content/css/nice-select.css">*@
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/css/select2-bootstrap.css">


    @RenderSection("pageStyles", required: false)
</head>
<body>

    <div class="body_bg">
        <!--::header part start::-->
        <header class="main_menu single_page_menu">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-12">
                        <nav class="navbar navbar-expand-lg navbar-light">
                            <a class="navbar-brand" href="@Url.Action("Index","Home")"> <img height="70" src="~/Content/img/rpgWorldLogo.png" alt="logo"> </a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse"
                                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                    aria-expanded="false" aria-label="Toggle navigation">
                                <span class="menu_icon"><em class="fas fa-bars"></em></span>
                            </button>

                            <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                                <ul class="navbar-nav">
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown"
                                           role="button" data-toggle="dropdown" aria-haspopup="true"
                                           aria-expanded="false">
                                            Yaratımlar
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            @Html.ActionLink("Evrenini Yarat", "Create", "Universe", null, new { @class = "dropdown-item" })
                                            @Html.ActionLink("Dünyanı Yarat", "Create", "Planet", null, new { @class = "dropdown-item" })
                                            @Html.ActionLink("Karakterini Yarat", "Create", "Character", null, new { @class = "dropdown-item" })
                                            @Html.ActionLink("Maceranı Yarat", "Create", "Campaign", null, new { @class = "dropdown-item" })
                                        </div>
                                    </li>
                                    <li class="nav-item">
                                        @Html.ActionLink("Hikayeler", "ViewAll", "Lores", null, new { @class = "nav-link" })
                                    </li>
                                    <li class="nav-item">
                                        @Html.ActionLink("Hikayeler", "ViewAll", "Sources", null, new { @class = "nav-link" })
                                    </li>
                                    @if (currentUser != null)
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("SignOut", "Sign")">Çıkış Yap</a>
                                        </li>
                                    }
                                </ul>
                            </div>
                            @if (currentUser != null)
                            {
                                <a href="@Url.Action("ViewProfile", "Profile", new { id = currentUser.UserID })" class="genric-btn danger d-none d-sm-block">@currentUser.Fullname</a>
                            }
                            else
                            {
                                <a href="@Url.Action("SignUp", "Sign")" class="genric-btn danger d-none d-sm-block">Kayıt Ol</a>
                                <a href="@Url.Action("SignIn", "Sign")" class="genric-btn danger d-sm-block">Giriş Yap</a>
                            }
                        </nav>
                    </div>
                </div>
            </div>
        </header>
        <!-- Header part end-->


        <div>
            @RenderBody()
        </div>


        <!--::footer_part start::-->
        <footer class="footer_part">
            <div class="footer_top">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6 col-lg-3">
                            <div class="single_footer_part">
                                <a href="index.html" class="footer_logo_iner"> <img src="~/Content/img/logo.png" alt="#"> </a>
                                <p>
                                    Devam eden maceranı yazdığın evrenle beraber oluşturup tarihini oluşturabilirsin. Karakterlerin efsanelere konuk olabilir, evreninin hikayesini oluşturabilirsin
                                </p>
                            </div>
                        </div>
                        <div class="col-sm-6 col-lg-3">
                            <div class="single_footer_part">
                                <h4>İletişim</h4>
                                <p>Email : info@dndworld.net</p>
                            </div>
                        </div>
                        <div class="col-sm-6 col-lg-3">
                            <div class="single_footer_part">
                                <h4>Important Link</h4>
                                <ul class="list-unstyled">
                                    <li><a href=""> WHMCS-bridge</a></li>
                                    <li><a href="">Search Domain</a></li>
                                    <li><a href="">My Account</a></li>
                                    <li><a href="">Shopping Cart</a></li>
                                    <li><a href="">Our Shop</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-sm-6 col-lg-3">
                            <div class="single_footer_part">
                                <h4>Newsletter</h4>
                                <p>
                                    Heaven fruitful doesn't over lesser in days. Appear creeping seasons deve behold
                                    bearing
                                    days
                                    open
                                </p>
                                <div id="mc_embed_signup">
                                    <form target="_blank"
                                          action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                          method="get" class="subscribe_form relative mail_part">
                                        <input type="email" name="email" id="newsletter-form-email"
                                               placeholder="Email Address" class="placeholder hide-on-focus"
                                               onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = ' Email Address '">
                                        <button type="submit" name="submit" id="newsletter-submit"
                                                class="email_icon newsletter-submit button-contactForm">
                                            <em class="far fa-paper-plane"></em>
                                        </button>
                                        <div class="mt-10 info"></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copygight_text">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-8">
                            <div class="copyright_text">
                                <P>
                                    @DateTime.Now.Year Tüm hakları saklıdır. DnDWorld
                                </P>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="footer_icon social_icon">
                                <ul class="list-unstyled">
                                    <li>
                                        <a href="#" class="single_social_icon"><em class="fab fa-facebook-f"></em></a>
                                    </li>
                                    <li><a href="#" class="single_social_icon"><em class="fab fa-twitter"></em></a></li>
                                    <li><a href="#" class="single_social_icon"><em class="fas fa-globe"></em></a></li>
                                    <li><a href="#" class="single_social_icon"><em class="fab fa-behance"></em></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!--::footer_part end::-->
    </div>


    <!-- jquery plugins here-->
    <script src="~/Content/js/jquery-1.12.1.min.js"></script>
    <script src="~/Content/js/popper.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/jquery.magnific-popup.js"></script>
    <script src="~/Content/js/swiper.min.js"></script>
    <script src="~/Content/js/masonry.pkgd.js"></script>
    <script src="~/Content/js/owl.carousel.min.js"></script>
    <script src="~/Content/js/slick.min.js"></script>
    <script src="~/Content/js/jquery.counterup.min.js"></script>
    <script src="~/Content/js/waypoints.min.js"></script>
    <script src="~/Content/js/contact.js"></script>
    <script src="~/Content/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/Content/js/jquery.form.js"></script>
    <script src="~/Content/js/jquery.validate.min.js"></script>
    <script src="~/Content/js/mail-script.js"></script>
    @*<script src="~/Content/js/jquery.nice-select.min.js"></script>*@

    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js"></script>
    <script src="~/Content/js/custom.js"></script>


    @RenderSection("pageScripts", required: false)
</body>
</html>